### ISSUE TITLE
Veil-Evasion.py loading error. 

### ISSUE THREAD

**Issue by butter12** [Veil-Framework/Veil-Evasion#248]
Traceback (most recent call last):
  File "./Veil-Evasion.py", line 290, in <module>
    controller = controller.Controller(oneRun=False)
  File "/usr/share/veil-evasion/modules/common/controller.py", line 107, in __init__
    self.LoadPayloads()
  File "/usr/share/veil-evasion/modules/common/controller.py", line 123, in LoadPayloads
    module = d[name].Payload()
  File "/root/Desktop/Veil-Evasion-master//modules/payloads/auxiliary/pyinstaller_wrapper.py", line 26, in __init__
    self.required_options["python_source"] = ["", "Python source file to compile with pyinstaller"]
AttributeError: Payload instance has no attribute 'required_options'

Ever since i updated from 2.17 to the newer version i get this error.  any ideal on this.

thanks.

**Comment by ChrisTruncer** [comment]
Can you please try installing on a clean version of Kali? That payload wasn't touched in any way, so it leads me to think there is something else odd on your system.

**Comment by ChrisTruncer** [comment]
Closing this since I haven't heard back.
